const fields = [
    { name: "👤 Character name", type: "text", placeholder: "First name + last name, or single name if applicable", tags: [
    ] },
    { name: "📝 Full name", type: "text", placeholder: "Legal or complete name, including middle names if any", tags: [
    ] },
    { name: "🏷️ Nickname", type: "text", placeholder: "Common nicknames, aliases, or what others usually call them", tags: [
    ] },
    { name: "🎂 Age", type: "text", placeholder: "Current age + whether it changes over time if relevant", tags: [
        { text: "16", color: "green" },
        { text: "18", color: "green" },
        { text: "21", color: "blue" },
        { text: "25", color: "blue" },
        { text: "30", color: "blue" },
        { text: "40", color: "orange" },
        { text: "Teen", color: "green" },
        { text: "Young adult", color: "blue" },
        { text: "Adult", color: "blue" },
        { text: "Middle-aged", color: "orange" },
        { text: "Elder", color: "purple" },
        { text: "Immortal", color: "purple" },
        { text: "Ageless", color: "purple" },
        { text: "Ancient", color: "purple" },
        { text: "Unknown", color: "yellow" },
        { text: "Centuries old", color: "purple" }
    ] },
    { name: "📏 Height", type: "text", placeholder: "Height in preferred units + any notable proportions", tags: [
        { text: "4'10\"", color: "yellow" },
        { text: "5'0\"", color: "yellow" },
        { text: "5'3\"", color: "green" },
        { text: "5'6\"", color: "green" },
        { text: "5'9\"", color: "blue" },
        { text: "6'0\"", color: "blue" },
        { text: "6'2\"", color: "blue" },
        { text: "6'5\"", color: "purple" },
        { text: "Tall", color: "blue" },
        { text: "Short", color: "yellow" },
        { text: "Average", color: "green" },
        { text: "Gigantic", color: "purple" },
        { text: "Tiny", color: "yellow" },
        { text: "Statuesque", color: "blue" },
        { text: "Towering", color: "purple" },
        { text: "Petite", color: "yellow" }
    ] },
    { name: "🎉 Birthday", type: "text", placeholder: "Date of birth + zodiac sign if desired", tags: [
        { text: "January 1st", color: "blue" },
        { text: "March 21st", color: "green" },
        { text: "June 15th", color: "yellow" },
        { text: "October 31st", color: "orange" },
        { text: "December 25th", color: "red" },
        { text: "Unknown", color: "purple" },
        { text: "Spring", color: "green" },
        { text: "Summer", color: "yellow" },
        { text: "Autumn", color: "orange" },
        { text: "Winter", color: "blue" },
        { text: "Aries ♈", color: "red" },
        { text: "Taurus ♉", color: "green" },
        { text: "Gemini ♊", color: "yellow" },
        { text: "Cancer ♋", color: "blue" },
        { text: "Leo ♌", color: "orange" },
        { text: "Virgo ♍", color: "green" },
        { text: "Libra ♎", color: "blue" },
        { text: "Scorpio ♏", color: "purple" },
        { text: "Sagittarius ♐", color: "orange" },
        { text: "Capricorn ♑", color: "blue" },
        { text: "Aquarius ♒", color: "blue" },
        { text: "Pisces ♓", color: "purple" }
    ] },
    { name: "⚧️ Gender", type: "text", placeholder: "Gender identity + pronouns", tags: [
        { text: "Male (he/him)", color: "blue" },
        { text: "Female (she/her)", color: "purple" },
        { text: "Non-binary (they/them)", color: "yellow" },
        { text: "Genderfluid", color: "rainbow" },
        { text: "Agender", color: "green" },
        { text: "Bigender", color: "orange" },
        { text: "Transgender", color: "blue" },
        { text: "Demiboy", color: "blue" },
        { text: "Demigirl", color: "purple" },
        { text: "Genderqueer", color: "rainbow" }
    ] },
    { name: "⭐ Attributes", type: "textarea", placeholder: "Key traits such as strength, intelligence, agility, charisma, etc.", tags: [
        { text: "Intelligent", color: "blue" },
        { text: "Strong", color: "red" },
        { text: "Agile", color: "green" },
        { text: "Charismatic", color: "purple" },
        { text: "Cunning", color: "orange" },
        { text: "Wise", color: "blue" },
        { text: "Bold", color: "red" },
        { text: "Creative", color: "purple" },
        { text: "Resilient", color: "green" },
        { text: "Brave", color: "red" },
        { text: "Observant", color: "blue" },
        { text: "Mysterious", color: "purple" },
        { text: "Charming", color: "purple" },
        { text: "Calculating", color: "blue" },
        { text: "Dexterous", color: "green" },
        { text: "Enduring", color: "green" },
        { text: "Perceptive", color: "blue" },
        { text: "Powerful", color: "red" },
        { text: "Quick-witted", color: "yellow" },
        { text: "Tactical", color: "blue" }
    ] },
    { name: "🧠 Personality", type: "textarea", placeholder: "Core personality traits, behavior patterns, strengths, flaws", tags: [
        { text: "Confident", color: "red" },
        { text: "Shy", color: "blue" },
        { text: "Mysterious", color: "purple" },
        { text: "Friendly", color: "green" },
        { text: "Sarcastic", color: "orange" },
        { text: "Kind", color: "green" },
        { text: "Ambitious", color: "red" },
        { text: "Loyal", color: "blue" },
        { text: "Stubborn", color: "red" },
        { text: "Witty", color: "yellow" },
        { text: "Hot-headed", color: "red" },
        { text: "Calm", color: "blue" },
        { text: "Optimistic", color: "yellow" },
        { text: "Pessimistic", color: "purple" },
        { text: "Cheerful", color: "yellow" },
        { text: "Reserved", color: "blue" },
        { text: "Impulsive", color: "red" },
        { text: "Analytical", color: "blue" },
        { text: "Adventurous", color: "orange" },
        { text: "Cautious", color: "green" },
        { text: "Playful", color: "yellow" },
        { text: "Serious", color: "purple" },
        { text: "Compassionate", color: "green" },
        { text: "Ruthless", color: "red" },
        { text: "Gentle", color: "green" },
        { text: "Fierce", color: "red" },
        { text: "Eccentric", color: "yellow" },
        { text: "Temperamental", color: "red" },
        { text: "Introverted", color: "blue" },
        { text: "Extroverted", color: "green" },
        { text: "Idealistic", color: "purple" },
        { text: "Pragmatic", color: "blue" },
        { text: "Manipulative", color: "red" },
        { text: "Naive", color: "yellow" },
        { text: "Empathetic", color: "green" },
        { text: "Cynical", color: "purple" },
        { text: "Energetic", color: "yellow" },
        { text: "Moody", color: "red" },
        { text: "Reserved", color: "blue" }, // reinforcement
        { text: "Optimistic", color: "yellow" }, // reinforcement
        { text: "Pessimistic", color: "purple" }, // reinforcement
        { text: "Honest", color: "green" },
        { text: "Secretive", color: "purple" },
        { text: "Resourceful", color: "blue" },
        { text: "Selfish", color: "red" },
        { text: "Forgiving", color: "green" }

    ] },
    { name: "🐉 Species", type: "text", placeholder: "Human or non-human species + subtype if applicable", tags: [
        { text: "Human", color: "blue" },
        { text: "Elf", color: "green" },
        { text: "Dark Elf", color: "purple" },
        { text: "Vampire", color: "red" },
        { text: "Demon", color: "red" },
        { text: "Angel", color: "yellow" },
        { text: "Fallen Angel", color: "purple" },
        { text: "Werewolf", color: "orange" },
        { text: "Dragon", color: "red" },
        { text: "Dragonborn", color: "orange" },
        { text: "Cyborg", color: "blue" },
        { text: "Android", color: "blue" },
        { text: "Fairy", color: "purple" },
        { text: "Merfolk", color: "blue" },
        { text: "Alien", color: "green" },
        { text: "Spirit", color: "purple" },
        { text: "Hybrid", color: "rainbow" },
        { text: "Witch", color: "purple" },
        { text: "Shapeshifter", color: "rainbow" },
        { text: "Zombie", color: "green" },
        { text: "Ghost", color: "blue" },
        { text: "Nephilim", color: "yellow" },
        { text: "Tiefling", color: "red" }
    ] },
    { name: "🎯 Skills", type: "textarea", placeholder: "Learned abilities, talents, combat skills, or special knowledge", tags: [
        { text: "Swordsmanship", color: "red" },
        { text: "Magic", color: "purple" },
        { text: "Hacking", color: "blue" },
        { text: "Medicine", color: "green" },
        { text: "Stealth", color: "purple" },
        { text: "Leadership", color: "orange" },
        { text: "Cooking", color: "yellow" },
        { text: "Music", color: "purple" },
        { text: "Archery", color: "green" },
        { text: "Martial arts", color: "red" },
        { text: "Strategy", color: "blue" },
        { text: "Alchemy", color: "purple" },
        { text: "Engineering", color: "blue" },
        { text: "Artistry", color: "purple" },
        { text: "Negotiation", color: "orange" },
        { text: "Singing", color: "yellow" },
        { text: "Dancing", color: "purple" },
        { text: "Hunting", color: "green" },
        { text: "Tracking", color: "green" },
        { text: "Lockpicking", color: "orange" },
        { text: "Persuasion", color: "purple" },
        { text: "Intimidation", color: "red" },
        { text: "Healing", color: "green" },
        { text: "Telekinesis", color: "blue" }
    ] },
    { name: "💖 Sexuality", type: "text", placeholder: "Sexual orientation + romantic preferences if relevant", tags: [
        { text: "Heterosexual", color: "blue" },
        { text: "Homosexual", color: "purple" },
        { text: "Bisexual", color: "purple" },
        { text: "Pansexual", color: "rainbow" },
        { text: "Asexual", color: "green" },
        { text: "Demisexual", color: "blue" },
        { text: "Queer", color: "rainbow" },
        { text: "Fluid", color: "rainbow" },
        { text: "Graysexual", color: "blue" },
        { text: "Polysexual", color: "purple" },
        { text: "Aromantic", color: "green" },
        { text: "Questioning", color: "yellow" }
    ] },
    { name: "🌍 Nationality", type: "text", placeholder: "Country of origin + cultural background", tags: [
        { text: "American", color: "blue" },
        { text: "Japanese", color: "red" },
        { text: "British", color: "blue" },
        { text: "French", color: "purple" },
        { text: "German", color: "orange" },
        { text: "Chinese", color: "red" },
        { text: "Italian", color: "green" },
        { text: "Spanish", color: "orange" },
        { text: "Russian", color: "red" },
        { text: "Korean", color: "blue" },
        { text: "Indian", color: "orange" },
        { text: "Brazilian", color: "green" },
        { text: "Multicultural", color: "rainbow" },
        { text: "Fantasy realm", color: "purple" },
        { text: "Alien world", color: "blue" },
        { text: "Unknown", color: "yellow" },
        { text: "Nomadic", color: "green" },
        { text: "Island nation", color: "blue" }
    ] },
    { name: "🔄 Habits", type: "textarea", placeholder: "Daily routines, nervous habits, good or bad behaviors", tags: [
        { text: "Coffee addict", color: "orange" },
        { text: "Night owl", color: "purple" },
        { text: "Early riser", color: "yellow" },
        { text: "Nail biting", color: "red" },
        { text: "Fidgeting", color: "yellow" },
        { text: "Smoking", color: "red" },
        { text: "Reading", color: "blue" },
        { text: "Exercising", color: "green" },
        { text: "Meditating", color: "purple" },
        { text: "Procrastinator", color: "orange" },
        { text: "Collector", color: "blue" },
        { text: "Joker", color: "yellow" },
        { text: "Planner", color: "blue" },
        { text: "Gamer", color: "purple" },
        { text: "Social butterfly", color: "rainbow" },
        { text: "Loner", color: "blue" },
        { text: "Workaholic", color: "red" },
        { text: "Perfectionist", color: "purple" },
        { text: "Messy", color: "orange" },
        { text: "Organized", color: "green" },
        { text: "Obsessive", color: "red" },
        { text: "Perfectionist", color: "purple" }, // reinforcement
        { text: "Forgetful", color: "yellow" },
        { text: "Talkative", color: "green" },
        { text: "Quiet", color: "blue" },
        { text: "Fidgety", color: "yellow" }, // reinforcement
        { text: "Nighttime wanderer", color: "purple" },
        { text: "Daydreamer", color: "yellow" },
        { text: "Collector of oddities", color: "blue" },
        { text: "Tinkerer", color: "green" },
        { text: "Compulsive planner", color: "blue" },
        { text: "Impulsive spender", color: "red" },
        { text: "Prone to procrastination", color: "orange" }, // reinforcement
        { text: "Meditative", color: "purple" }, // reinforcement
        { text: "Gossiper", color: "orange" },
        { text: "Polite", color: "green" },
        { text: "Sarcastic humor", color: "orange" }, // reinforcement
        { text: "Superstitious", color: "yellow" },
        { text: "Competitive", color: "red" }

    ] },
    { name: "🎨 Hobbies", type: "textarea", placeholder: "Activities they enjoy in their free time", tags: [
        { text: "Reading", color: "blue" },
        { text: "Gaming", color: "purple" },
        { text: "Drawing", color: "purple" },
        { text: "Sports", color: "red" },
        { text: "Music", color: "purple" },
        { text: "Cooking", color: "orange" },
        { text: "Hiking", color: "green" },
        { text: "Photography", color: "blue" },
        { text: "Writing", color: "blue" },
        { text: "Dancing", color: "purple" },
        { text: "Fishing", color: "blue" },
        { text: "Gardening", color: "green" },
        { text: "Collecting", color: "yellow" },
        { text: "Crafting", color: "orange" },
        { text: "Traveling", color: "rainbow" },
        { text: "Meditation", color: "purple" },
        { text: "Painting", color: "purple" },
        { text: "Chess", color: "blue" },
        { text: "Stargazing", color: "purple" },
        { text: "Martial arts", color: "red" }
    ] },
    { name: "💪 Body", type: "textarea", placeholder: "Body type, build, scars, tattoos, or notable physical traits", tags: [
        { text: "Athletic", color: "red" },
        { text: "Slender", color: "blue" },
        { text: "Muscular", color: "red" },
        { text: "Curvy", color: "purple" },
        { text: "Scarred", color: "red" },
        { text: "Tattooed", color: "purple" },
        { text: "Petite", color: "yellow" },
        { text: "Tall", color: "blue" },
        { text: "Stocky", color: "orange" },
        { text: "Lean", color: "green" },
        { text: "Brawny", color: "red" },
        { text: "Elegant", color: "purple" },
        { text: "Lithe", color: "green" },
        { text: "Flexible", color: "green" },
        { text: "Toned", color: "red" },
        { text: "Soft", color: "blue" },
        { text: "Rugged", color: "orange" },
        { text: "Delicate", color: "purple" },
        { text: "Battle-worn", color: "red" },
        { text: "Pierced", color: "purple" }
    ] },
    { name: "✨ Appearance", type: "textarea", placeholder: "Overall look including hair, eyes, clothing style, aesthetic", tags: [
        { text: "Dark hair", color: "purple" },
        { text: "Blonde hair", color: "yellow" },
        { text: "Red hair", color: "red" },
        { text: "White hair", color: "blue" },
        { text: "Blue eyes", color: "blue" },
        { text: "Green eyes", color: "green" },
        { text: "Brown eyes", color: "orange" },
        { text: "Heterochromic", color: "rainbow" },
        { text: "Casual style", color: "blue" },
        { text: "Gothic", color: "purple" },
        { text: "Elegant", color: "purple" },
        { text: "Messy", color: "orange" },
        { text: "Well-groomed", color: "green" },
        { text: "Mysterious", color: "purple" },
        { text: "Colorful", color: "rainbow" },
        { text: "Punk", color: "red" },
        { text: "Fantasy armor", color: "orange" },
        { text: "Magical aura", color: "purple" },
        { text: "Scarred face", color: "red" },
        { text: "Glowing eyes", color: "yellow" },
        { text: "Vintage style", color: "green" },
        { text: "Street wear", color: "blue" },
        { text: "Formal attire", color: "purple" },
        { text: "Bohemian", color: "rainbow" },
        { text: "Platinum hair", color: "blue" },
        { text: "Ombre hair", color: "rainbow" },
        { text: "Curly hair", color: "yellow" },
        { text: "Straight hair", color: "green" },
        { text: "Braided hair", color: "purple" },
        { text: "Piercing eyes", color: "red" },
        { text: "Freckles", color: "yellow" },
        { text: "Beauty mark", color: "green" },
        { text: "Elaborate makeup", color: "purple" },
        { text: "Scar across body", color: "red" },
        { text: "Exotic clothing", color: "rainbow" },
        { text: "Minimalist style", color: "blue" },
        { text: "Elegant armor", color: "purple" },
        { text: "Steampunk attire", color: "orange" },
        { text: "Fantasy robes", color: "purple" },
        { text: "Flowing cape", color: "blue" },
        { text: "Tattoos", color: "purple" }, // reinforcement
        { text: "Glowing markings", color: "yellow" },
        { text: "Mechanical augmentations", color: "blue" }

    ] },
    { name: "🗣️ Language", type: "text", placeholder: "Languages spoken + fluency levels", tags: [
        { text: "English (fluent)", color: "blue" },
        { text: "Spanish (fluent)", color: "orange" },
        { text: "Japanese (fluent)", color: "red" },
        { text: "French (fluent)", color: "purple" },
        { text: "German", color: "orange" },
        { text: "Chinese", color: "red" },
        { text: "Korean", color: "blue" },
        { text: "Italian", color: "green" },
        { text: "Multiple languages", color: "rainbow" },
        { text: "Polyglot", color: "rainbow" },
        { text: "Unknown tongue", color: "purple" },
        { text: "Elvish", color: "green" },
        { text: "Dwarvish", color: "orange" },
        { text: "Draconic", color: "red" },
        { text: "Sign language", color: "blue" },
        { text: "Ancient language", color: "purple" },
        { text: "Telepathy", color: "purple" }
    ] },
    { name: "❤️ Love language", type: "text", placeholder: "How they show and receive affection", tags: [
        { text: "Physical touch", color: "red" },
        { text: "Words of affirmation", color: "blue" },
        { text: "Acts of service", color: "green" },
        { text: "Quality time", color: "purple" },
        { text: "Gift giving", color: "yellow" },
        { text: "Flirting", color: "purple" },
        { text: "Protective", color: "red" },
        { text: "Teasing", color: "orange" },
        { text: "Compliments", color: "yellow" },
        { text: "Cooking for them", color: "orange" },
        { text: "Listening", color: "blue" },
        { text: "Loyalty", color: "blue" },
        { text: "Thoughtful gestures", color: "green" }
    ] },
    { name: "💼 Occupation", type: "text", placeholder: "Job, role, or primary function in their world", tags: [
        { text: "Student", color: "blue" },
        { text: "Warrior", color: "red" },
        { text: "Detective", color: "blue" },
        { text: "Artist", color: "purple" },
        { text: "Scientist", color: "blue" },
        { text: "Assassin", color: "red" },
        { text: "Teacher", color: "green" },
        { text: "Doctor", color: "green" },
        { text: "Merchant", color: "orange" },
        { text: "Politician", color: "purple" },
        { text: "Mage", color: "purple" },
        { text: "Engineer", color: "blue" },
        { text: "Explorer", color: "green" },
        { text: "Thief", color: "purple" },
        { text: "Knight", color: "red" },
        { text: "Pirate", color: "orange" },
        { text: "Bounty hunter", color: "red" },
        { text: "Chef", color: "orange" },
        { text: "Musician", color: "purple" },
        { text: "Spy", color: "purple" }
    ] },
    { name: "👍 Likes", type: "textarea", placeholder: "Things, people, or experiences they enjoy", tags: [
        { text: "Coffee", color: "orange" },
        { text: "Rain", color: "blue" },
        { text: "Books", color: "blue" },
        { text: "Music", color: "purple" },
        { text: "Adventure", color: "red" },
        { text: "Quiet moments", color: "blue" },
        { text: "Animals", color: "green" },
        { text: "Nature", color: "green" },
        { text: "Traveling", color: "rainbow" },
        { text: "Food", color: "orange" },
        { text: "Art", color: "purple" },
        { text: "Magic", color: "purple" },
        { text: "Technology", color: "blue" },
        { text: "Friendship", color: "yellow" },
        { text: "Stars", color: "purple" },
        { text: "Ocean", color: "blue" },
        { text: "Mountains", color: "green" },
        { text: "Sweets", color: "yellow" }
    ] },
    { name: "👎 Dislikes", type: "textarea", placeholder: "Things they avoid, hate, or feel uncomfortable with", tags: [
        { text: "Crowds", color: "red" },
        { text: "Dishonesty", color: "red" },
        { text: "Loud noises", color: "orange" },
        { text: "Betrayal", color: "red" },
        { text: "Heat", color: "orange" },
        { text: "Cold", color: "blue" },
        { text: "Injustice", color: "red" },
        { text: "Being controlled", color: "red" },
        { text: "Failure", color: "purple" },
        { text: "Rules", color: "orange" },
        { text: "Spicy food", color: "red" },
        { text: "Snakes", color: "green" },
        { text: "Silence", color: "blue" },
        { text: "Chaos", color: "red" },
        { text: "Violence", color: "red" },
        { text: "Boredom", color: "yellow" },
        { text: "Authority", color: "red" },
        { text: "Weakness", color: "purple" }
    ] },
    { name: "🎭 Roleplay", type: "textarea", placeholder: "How they act in roleplay scenarios, tone, boundaries, dynamics", tags: [
        { text: "Dominant", color: "red" },
        { text: "Submissive", color: "purple" },
        { text: "Switch", color: "rainbow" },
        { text: "Playful", color: "yellow" },
        { text: "Serious", color: "blue" },
        { text: "Flirty", color: "purple" },
        { text: "Reserved", color: "blue" },
        { text: "Aggressive", color: "red" },
        { text: "Protective", color: "red" },
        { text: "Mischievous", color: "orange" },
        { text: "Romantic", color: "purple" },
        { text: "Stoic", color: "blue" },
        { text: "Teasing", color: "orange" },
        { text: "Caring", color: "green" },
        { text: "Intense", color: "red" },
        { text: "Gentle", color: "green" }
    ] },
    { name: "📖 Backstory", type: "textarea", placeholder: "Important past events that shaped who they are", tags: [
        { text: "Tragic past", color: "purple" },
        { text: "Noble upbringing", color: "blue" },
        { text: "Mysterious origins", color: "purple" },
        { text: "Self-made", color: "green" },
        { text: "Abandoned", color: "blue" },
        { text: "Trained warrior", color: "red" },
        { text: "Orphaned", color: "blue" },
        { text: "Royal lineage", color: "purple" },
        { text: "Exiled", color: "orange" },
        { text: "Lost love", color: "purple" },
        { text: "Secret heritage", color: "purple" },
        { text: "War survivor", color: "red" },
        { text: "Street urchin", color: "orange" },
        { text: "Betrayed", color: "red" },
        { text: "Cursed", color: "purple" },
        { text: "Blessed", color: "yellow" },
        { text: "Prodigy", color: "blue" },
        { text: "Redemption arc", color: "green" }
    ] }
];
